### ISSUE TITLE
Data Sourcing Error

### ISSUE THREAD

**Issue by llax11** [PacktPublishing/Learning-Tableau-2022#2]
When attempting to begin manipulating the data for "Chapter 3 Starter.twbx" the following error appears within Tableau:

Unable to complete action
There was a problem connecting to the data source "Hospital Visits & Revenue".
Error Code: 88A6ADA0
File: /var/folders/4v/jbz9p3m947s953qm9jrv17x80000gn/T/tableau-temp/1808245952/Data/Chapter 03/C:/Users/jmilligan/Documents/Work/VizPainter/Books/Learning Tableau 2020/Learning Tableau/Chapter 03/C:\Users\jmilligan\Documents\Work\VizPainter\Books\Learning Tableau 2020\Learning Tableau\Chapter 03\Hospital Goals.csv not found. Please edit the connection

Thanks in advance for any help or guidance.

**Comment by Sonawane-Karan26** [comment]
Hi, I think you'll have to redirect to your current folder structure.
I think your working directly still points to the 'Learning Tableau 2020' folder.

If this doesn't help, you can download the file from this GitHub and place it in your working folder.
